# Generated by Django 5.2.12 on 2026-03-31 12:06

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('anonymous', 'Anonymous (belum login)'), ('registered', 'Registered user')], max_length=15, unique=True)),
                ('max_secrets_per_day', models.PositiveSmallIntegerField(default=3)),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=10)),
                ('max_recipients', models.PositiveSmallIntegerField(default=10, help_text='Maks jumlah link (penerima) per secret.')),
                ('max_expiry_days', models.PositiveSmallIntegerField(default=7, help_text='Maks berapa hari secret bisa di-set expire. 0 = tidak ada batas.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Config',
                'verbose_name_plural': 'Rate Limit Configs',
                'db_table': 'rate_limit_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_secrets_created', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('daily_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonymous Session',
                'verbose_name_plural': 'Anonymous Sessions',
                'db_table': 'anonymous_sessions',
                'indexes': [models.Index(fields=['ip_address'], name='anonymous_s_ip_addr_1a42bd_idx'), models.Index(fields=['fingerprint_hash'], name='anonymous_s_fingerp_51d356_idx'), models.Index(fields=['last_reset_date'], name='anonymous_s_last_re_815ad5_idx')],
                'unique_together': {('ip_address', 'fingerprint_hash')},
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_type', models.CharField(choices=[('text', 'Teks'), ('password', 'Password'), ('file', 'File'), ('note', 'Catatan')], max_length=10)),
                ('original_filename', models.CharField(blank=True, help_text='Nama file asli (hanya untuk tipe file). Disimpan terenkripsi terpisah opsional.', max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Ukuran file dalam bytes sebelum enkripsi.', null=True)),
                ('encrypted_payload', models.TextField(help_text='Ciphertext base64 hasil enkripsi AES-256-GCM di browser.')),
                ('encryption_iv', models.CharField(help_text='Nonce 96-bit, base64. Unik per secret.', max_length=32)),
                ('encryption_tag', models.CharField(help_text='GCM auth tag 128-bit, base64.', max_length=32)),
                ('encryption_salt', models.CharField(blank=True, help_text='Salt PBKDF2 base64. Diisi jika key di-derive dari password user.', max_length=64)),
                ('max_views', models.PositiveSmallIntegerField(default=1, help_text='Maks berapa kali link bisa dibuka. 0 = unlimited (hanya untuk user login).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('current_views', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = tidak ada expiry (hanya untuk user login).', null=True)),
                ('access_password_hash', models.CharField(blank=True, help_text='Bcrypt hash dari password tambahan untuk akses link. Kosong = tidak ada password.', max_length=128)),
                ('revoke_token', models.CharField(default=api.models.generate_revoke_token, help_text='Token rahasia untuk revoke secret tanpa perlu login. Dikembalikan sekali ke creator.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('revoked', 'Dicabut'), ('expired', 'Kedaluwarsa'), ('blocked', 'Diblokir Admin')], db_index=True, default='active', max_length=10)),
                ('ai_risk_score', models.PositiveSmallIntegerField(default=0, help_text='Risk score 0–100 dari AI detection di browser/metadata server.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_flagged', models.BooleanField(default=False, help_text='True jika perlu review admin (score 40–69).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Kapan secret ini di-expire oleh sistem (beda dari expires_at yang di-set user).', null=True)),
                ('anon_session', models.ForeignKey(blank=True, help_text='Null jika dibuat oleh user terdaftar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrets', to='api.anonymoussession')),
                ('creator_user', models.ForeignKey(blank=True, help_text='Null jika dibuat oleh anonymous user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
                'db_table': 'secrets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailWhitelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='Kapan email ini pertama kali berhasil mengakses secret.', null=True)),
                ('access_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_whitelist', to='api.secret')),
            ],
            options={
                'verbose_name': 'Email Whitelist',
                'verbose_name_plural': 'Email Whitelist',
                'db_table': 'email_whitelist',
            },
        ),
        migrations.CreateModel(
            name='AIDetectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('client', 'Browser (client-side scan)'), ('server', 'Server (metadata scan)')], max_length=10)),
                ('rules_triggered', models.JSONField(default=list, help_text="List rule yang terpicu. Contoh: ['pii_credit_card', 'keyword_malware']")),
                ('risk_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('action_taken', models.CharField(choices=[('allowed', 'Diizinkan'), ('flagged', 'Diflag untuk review'), ('blocked', 'Diblokir otomatis')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('secret_type', models.CharField(blank=True, max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(blank=True, help_text='Null jika secret diblokir sebelum disimpan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='api.secret')),
            ],
            options={
                'verbose_name': 'AI Detection Log',
                'verbose_name_plural': 'AI Detection Logs',
                'db_table': 'ai_detection_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=api.models.generate_short_token, help_text='Token URL-safe yang membentuk link: /s/{token}', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text="Label opsional untuk membedakan penerima. Contoh: 'Link untuk Alice'.", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('accessed_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.secret')),
            ],
            options={
                'verbose_name': 'Secret Link',
                'verbose_name_plural': 'Secret Links',
                'db_table': 'secret_links',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_by_email', models.EmailField(blank=True, help_text='Email accessor jika mereka memasukkan email untuk whitelist check.', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('result', models.CharField(choices=[('success', 'Berhasil'), ('denied_password', 'Password salah'), ('denied_email', 'Email tidak di whitelist'), ('denied_expired', 'Secret kedaluwarsa'), ('denied_revoked', 'Secret dicabut'), ('denied_exhausted', 'View count habis'), ('denied_blocked', 'Diblokir admin')], default='success', max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('secret_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='api.secretlink')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_banned'], name='users_is_bann_efe0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['status'], name='secrets_status_5528b1_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['expires_at'], name='secrets_expires_49f780_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['ai_flagged'], name='secrets_ai_flag_6ecc57_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['creator_user', 'created_at'], name='secrets_creator_1be29e_idx'),
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['revoke_token'], name='secrets_revoke__640911_idx'),
        ),
        migrations.AddIndex(
            model_name='emailwhitelist',
            index=models.Index(fields=['secret', 'email'], name='email_white_secret__25da0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailwhitelist',
            unique_together={('secret', 'email')},
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['action_taken'], name='ai_detectio_action__f182f8_idx'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['risk_score'], name='ai_detectio_risk_sc_c69aac_idx'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['source'], name='ai_detectio_source_fe9c23_idx'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['reviewed_at'], name='ai_detectio_reviewe_06b072_idx'),
        ),
        migrations.AddIndex(
            model_name='aidetectionlog',
            index=models.Index(fields=['created_at'], name='ai_detectio_created_779f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='secretlink',
            index=models.Index(fields=['token'], name='secret_link_token_7f0aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='secretlink',
            index=models.Index(fields=['secret', 'is_active'], name='secret_link_secret__37dd21_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['secret_link', 'accessed_at'], name='access_logs_secret__964d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['result'], name='access_logs_result_23bbac_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['ip_address'], name='access_logs_ip_addr_b362d7_idx'),
        ),
    ]
