# Generated by Django 5.2.12 on 2026-04-14 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainWhitelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain email. Contoh: companyabc.com (tanpa @)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_whitelist', to='api.secret')),
            ],
            options={
                'db_table': 'domain_whitelist',
                'unique_together': {('secret', 'domain')},
            },
        ),
    ]
