# Generated by Django 5.2.12 on 2026-04-29 01:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_domainwhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_flag', models.PositiveSmallIntegerField(default=40, help_text='Score ≥ ini → FLAGGED (review admin). Default: 40', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('score_block', models.PositiveSmallIntegerField(default=70, help_text='Score ≥ ini → BLOCKED otomatis. Default: 70', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('rate_burst_1min', models.PositiveSmallIntegerField(default=5, help_text='Maks request/menit per IP (anon)')),
                ('rate_burst_10min', models.PositiveSmallIntegerField(default=10, help_text='Maks request/10 menit per IP (anon)')),
                ('rate_burst_1hour', models.PositiveSmallIntegerField(default=30, help_text='Maks request/jam per IP (anon)')),
                ('rule_blocked_mime', models.BooleanField(default=True, help_text='Blokir MIME/ekstensi berbahaya')),
                ('rule_iv_reuse', models.BooleanField(default=True, help_text='Deteksi IV nonce dipakai ulang')),
                ('rule_rate_abuse', models.BooleanField(default=True, help_text='Rate abuse per IP')),
                ('rule_suspicious_filename', models.BooleanField(default=True, help_text='Nama file mencurigakan')),
                ('rule_entropy_anomaly', models.BooleanField(default=True, help_text='Entropy ciphertext rendah')),
                ('rule_payload_size', models.BooleanField(default=True, help_text='Ukuran payload tidak konsisten')),
                ('rule_suspicious_config', models.BooleanField(default=True, help_text='Konfigurasi secret tidak wajar')),
                ('rule_file_size_anomaly', models.BooleanField(default=True, help_text='Ukuran file anomali')),
                ('rule_suspicious_ua', models.BooleanField(default=True, help_text='User-agent bot/automation')),
                ('rule_client_amplifier', models.BooleanField(default=True, help_text='Amplifikasi score dari browser')),
                ('rule_combo_anon_abuse', models.BooleanField(default=True, help_text='Combo: anon + banyak penerima + tanpa proteksi')),
                ('rule_combo_malware_dist', models.BooleanField(default=True, help_text='Combo: file besar + anon + bot UA')),
                ('rule_combo_rapid_create', models.BooleanField(default=True, help_text='Combo: buat secret identik berulang dari IP sama')),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-increment saat disimpan. Dipakai sebagai cache key version.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Config',
                'db_table': 'detection_config',
            },
        ),
    ]
